<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CustomPostTypeAdditionalFields extends \App\Entities\CustomPostTypeAdditionalFields implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'id', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'label', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'fieldName', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'type', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'fieldValue', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'isRequired', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'customPostType'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'id', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'label', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'fieldName', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'type', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'fieldValue', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'isRequired', '' . "\0" . 'App\\Entities\\CustomPostTypeAdditionalFields' . "\0" . 'customPostType'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CustomPostTypeAdditionalFields $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldName', []);

        return parent::getFieldName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFieldName($fieldName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFieldName', [$fieldName]);

        return parent::setFieldName($fieldName);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldValue', []);

        return parent::getFieldValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setFieldValue($fieldValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFieldValue', [$fieldValue]);

        return parent::setFieldValue($fieldValue);
    }

    /**
     * {@inheritDoc}
     */
    public function isRequired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRequired', []);

        return parent::isRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRequired($isRequired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRequired', [$isRequired]);

        return parent::setIsRequired($isRequired);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomPostType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomPostType', []);

        return parent::getCustomPostType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomPostType($customPostType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomPostType', [$customPostType]);

        return parent::setCustomPostType($customPostType);
    }

}
