<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Job extends \App\Entities\Job implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'jobTitle', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'noOfOpenings', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'jobLocation', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'jobDescription', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'jobTiming', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'interviewDetails', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'company', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'isActive'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'jobTitle', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'noOfOpenings', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'jobLocation', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'jobDescription', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'jobTiming', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'interviewDetails', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'company', '' . "\0" . 'App\\Entities\\Job' . "\0" . 'isActive'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Job $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobTitle', []);

        return parent::getJobTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobTitle($jobTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobTitle', [$jobTitle]);

        return parent::setJobTitle($jobTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoOfOpenings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoOfOpenings', []);

        return parent::getNoOfOpenings();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoOfOpenings($noOfOpenings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoOfOpenings', [$noOfOpenings]);

        return parent::setNoOfOpenings($noOfOpenings);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobLocation', []);

        return parent::getJobLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobLocation($jobLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobLocation', [$jobLocation]);

        return parent::setJobLocation($jobLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobDescription', []);

        return parent::getJobDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobDescription($jobDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobDescription', [$jobDescription]);

        return parent::setJobDescription($jobDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobTiming()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobTiming', []);

        return parent::getJobTiming();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobTiming($jobTiming)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobTiming', [$jobTiming]);

        return parent::setJobTiming($jobTiming);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterviewDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterviewDetails', []);

        return parent::getInterviewDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterviewDetails($interviewDetails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterviewDetails', [$interviewDetails]);

        return parent::setInterviewDetails($interviewDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', []);

        return parent::getCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany($company)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', [$company]);

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

}
